extends: ~

scope:
    Object: Oxygen_Object
    Exception: Exception
    Scope: Oxygen_Scope
    Controller: Oxygen_Controller

views:
    inspected:
        access: public
        args: { value: Object }
        info: Put contents of given object in debug/inspectable form

    oxy:
        access: private
        args: { class: Object }
        info: Renders template

    exception:
        access: private
        args: { ex: Exception }
        info: Renders given exception

    exception_trace:
        access: private
        args: { trace: array }
        info: Renders given exception trace