extends: ~


scope: false # NEVER SET IT FOR Oxygen_Object

views:
    head:
        args:
            assets: array
        info: "Renders HTML document HEAD section contents"

    page:
        info: "Renders full HTML documnet representation suitable for displaying in browser"

    tile:
        info: "Renders given object as a tile"

    view:
        info: "Generic view of $this, suitable for embedding into other views"

    icon:
        info: "Small piece of html markup for dispalying the icon, assigned to $this"